# -*- coding: utf-8 -*-
"""Raneem_Ramadan_BCIS566_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLJa3NejCIUfwlK6YlHPOod4RsdIG5Og

Import Libraries
"""

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

tf.__version__

"""Import Dataset"""

dataset = pd.read_csv('housing.csv')

"""Variables"""

longitude = dataset['longitude']
latitude = dataset['latitude']
housing_median_age = dataset['housing_median_age']
total_rooms = dataset['total_rooms']
total_bedrooms = dataset['total_bedrooms'] # do I use this variable?
population = dataset['population']
households = dataset['households']
median_income = dataset['median_income']
median_house_value = dataset['median_house_value']
ocean_proximity = dataset['ocean_proximity']  #categorical data for classification analysis

#change value name for readability
dataset['ocean_proximity'] = dataset['ocean_proximity'].replace({
    '<1H OCEAN': 'Less than 1 Hour Ocean'
})
#To remove NaN preditions and errors. Takes missing bedroom value and replaced them with the median bedroom value.
dataset['total_bedrooms'] = dataset['total_bedrooms'].fillna(dataset['total_bedrooms'].median())

# convert category ocean proximity to numreric dummy variable.
dataset = pd.get_dummies(dataset, columns=['ocean_proximity'])
print(dataset.columns)


x = dataset[['longitude',
             'latitude',
             'housing_median_age',
             'total_rooms',
             'total_bedrooms',
             'population',
             'households',
             'median_income',
             'ocean_proximity_INLAND',
             'ocean_proximity_ISLAND',
             'ocean_proximity_Less than 1 Hour Ocean',
             'ocean_proximity_NEAR BAY',
             'ocean_proximity_NEAR OCEAN']]

            #do not incule ocean_proximity since it is categorical

y = dataset['median_house_value']

print(x)
print(y)

"""Correlation and Heatmap"""

plt.figure(figsize=(12,8))

sns.heatmap(
    dataset.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title("Correlation Heatmap of Housing Dataset")
plt.show()

print(dataset.isnull().sum())

"""Splitting Dataset Into Training and Testing"""

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0) #20% obesrvations in test set

"""Build Artificial Neural Network (ANN)"""

ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #adding an input layer and first hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #adding a second hidden layer

ann.add(tf.keras.layers.Dense(units=1)) #adding an output layer
#ann.add(tf.keras.layers.Dense(units=1, activation='relu')) #include activation funtion only in classification

"""Training ANN"""

ann.compile(optimizer = 'adam', loss = 'mean_squared_error') #compile ann
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

# predict results of test set
y_pred = ann.predict(x_test)

results = pd.DataFrame({
    'Predicted': y_pred.flatten(),
    'Actual': y_test.values
})

pd.options.display.float_format = '{:.2f}'.format
print(results)

"""Scatterplot for ANN"""

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, alpha=0.5)

plt.xlabel("Actual House Value")
plt.ylabel("Predicted House Value")
plt.title("ANN: Actual vs Predicted Values")

plt.show()

"""Plot Mean Squared Error during ANN raining"""

history = ann.fit(x_train, y_train,
                  batch_size=32,
                  epochs=100,
                  validation_split=0.2)

plt.figure(figsize=(8,6))

plt.plot(history.history['loss'], label='Training MSE')
plt.plot(history.history['val_loss'], label='Validation MSE')

plt.xlabel("Epoch")
plt.ylabel("Mean Squared Error")
plt.title("Model MSE During Training")
plt.legend()

plt.show()

"""R² from predictions"""

r2 = r2_score(y_test, y_pred)
print("R-squared:", round(r2,4))

"""Random Forest - Training"""

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=0,
    n_jobs=-1
)

rf.fit(x_train, y_train)

"""Predict and Evaluate"""

y_pred_rf = rf.predict(x_test)

r2 = r2_score(y_test, y_pred_rf)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))
mae = mean_absolute_error(y_test, y_pred_rf)

print("Random Forest R²:", round(r2,4))
print("RMSE:", round(rmse,2))
print("MAE:", round(mae,2))

"""Scatterplot for Random Forest"""

plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred_rf, alpha=0.5)

plt.xlabel("Actual House Value")
plt.ylabel("Predicted House Value")
plt.title("Random Forest: Actual vs Predicted")

plt.show()

# feature importance from Random Forest
importance = rf.feature_importances_

# create table
feat_imp = pd.DataFrame({
    'Feature': x.columns,
    'Importance': importance
})

# sort highest first
feat_imp = feat_imp.sort_values(by='Importance', ascending=False)

# Draw chart
plt.figure(figsize=(10,6))

plt.barh(feat_imp['Feature'], feat_imp['Importance'])

plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.title("Random Forest Feature Importance")

plt.show()